#!/usr/bin/env bun
import { $ } from 'bun';
import { existsSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';

const inputCss = './src/styles/input.css';
const tempCss = './src/styles/tailwind.tmp.css';
const outputFile = './src/styles/tailwind.generated.ts';

async function buildCss() {
  const dir = dirname(outputFile);
  if (!existsSync(dir)) {
    mkdirSync(dir, { recursive: true });
  }

  console.log('🎨 Compiling Tailwind CSS...');
  await $`bunx tailwindcss@3 -i ${inputCss} -o ${tempCss} --minify --config tailwind.config.js`;

  const minifiedCss = await Bun.file(tempCss).text();

  // Escape backticks and template string interpolations if any
  const escapedCss = minifiedCss.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$/g, '\\$');

  const tsContent = `// Auto-generated by scripts/build-css.ts - do not edit directly\nexport const COMPILED_TAILWIND_CSS = \`${escapedCss}\`;\n`;

  await Bun.write(outputFile, tsContent);
  await $`rm -f ${tempCss}`;

  const sizeKb = (Buffer.byteLength(minifiedCss, 'utf8') / 1024).toFixed(2);
  console.log(`✅ Tailwind CSS compiled successfully: ${outputFile} (${sizeKb} KB)`);
}

buildCss().catch((err) => {
  console.error('❌ Failed to compile Tailwind CSS:', err);
  process.exit(1);
});
