#!/usr/bin/env bun
import { Resvg } from '@resvg/resvg-js';
import { writeFileSync } from 'node:fs';
import { Buffer } from 'node:buffer';
import process from 'node:process';
import { generateSiteOgImageSvg } from '../src/services/seo';

const pngPath = './src/assets/og-default.png';
const tsPath = './src/assets/og-default.ts';

async function buildOg() {
  console.log('🖼️  Rendering static 1200x630 OG image from SVG...');
  const svg = generateSiteOgImageSvg();
  const resvg = new Resvg(svg, {
    fitTo: { mode: 'width', value: 1200 },
  });
  const pngData = resvg.render();
  const pngBuffer = pngData.asPng();

  writeFileSync(pngPath, pngBuffer);

  const base64 = Buffer.from(pngBuffer).toString('base64');
  const tsContent = `// Auto-generated by scripts/build-og.ts - do not edit directly
export const OG_DEFAULT_PNG_BASE64 = "${base64}";
export const OG_DEFAULT_PNG_BYTES = Uint8Array.from(atob(OG_DEFAULT_PNG_BASE64), (c) => c.charCodeAt(0));
`;

  writeFileSync(tsPath, tsContent);

  const sizeKb = (pngBuffer.length / 1024).toFixed(2);
  console.log(`✅ OG image rendered successfully: ${pngPath} (${sizeKb} KB)`);
}

buildOg().catch((err) => {
  console.error('❌ Failed to render OG image:', err);
  process.exit(1);
});
